#!/bin/sh

# --- Rubocop lint ---

echo "\nRunning rubocop 🚓 💨 💨 💨\n"

declare -a RUBOCOP_ERRORS=()

for file in $(git diff --cached --name-only | grep -E '\.rb$')
do
	RUBOCOP_ERRORS+=("$(docker-compose exec -T web rubocop $file | grep -e 'C:' -e 'E:')")
done

if [[ "$RUBOCOP_ERRORS" != "" ]]; then
	echo "\n 🚨 BEE-BOP! There are some things that you need to fix before commiting!\n"
	history -p "${RUBOCOP_ERRORS[@]}"
  exit 1
fi

echo "\n ✅ Done! Rubocop has no complains!\n"

# --- ERB lint ---
echo "\nRunning ERB lint 🚓 💨 💨 💨\n"

declare -a ERB_LINT_ERRORS=()

for file in $(git diff --cached --name-only | grep -E '\.erb$')
do
	ERB_LINT_ERRORS+=("$(docker-compose exec -T web bundle exec erblint --format compact $file | grep -e '\.erb:')")
done

if [[ "$ERB_LINT_ERRORS" != "" ]]; then
	echo "\n 🚨 BEE-BOP! There are some things that you need to fix before commiting!\n"
	history -p "${ERB_LINT_ERRORS[@]}"
  exit 1
fi

echo "\n ✅ Done! ERB lint has no complains!\n"

exit 0
