version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
  githooks:
    build:
      context: .
      dockerfile: 'Dockerfile.githooks'
    volumes:
      - ./.git:/tmp/.git
      - ./.githooks:/tmp/.githooks

volumes:
  pg_data:
  redis_data:
  bundle:
